image: golang

Test:
  stage: test

  before_script:
    - cd $GOPATH/src
    - mkdir -p gitlab.com/$CI_PROJECT_NAMESPACE
    - cd gitlab.com/$CI_PROJECT_NAMESPACE
    - ln -s $CI_PROJECT_DIR
    - cd $CI_PROJECT_NAME
    - go get github.com/gin-gonic/gin
    - go get github.com/adlio/trello
    - go get github.com/stretchr/testify/assert
    - go get github.com/jinzhu/gorm
    - go get github.com/mattn/go-sqlite3
    - git clone https://github.com/NguyenUmbala/trello-report-tools/

  script:
    - cd $GOPATH/src/gitlab.com/$CI_PROJECT_NAMESPACE
    - cd $CI_PROJECT_NAME
    - go test ./...