deploy-test:
  before_script:
    - 'which ssh-agent || ( yum update -y && yum install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - whoami
    - cd /var/www/html/project_folder
  script:
    - git pull
    - cp app/install/.server_test_db.php app/config/database.php 
    - php index.php migrate
  only:
    - test-server